import { bot } from './bot.js';

// Comandos exibidos no menu do Telegram.
const COMANDOS = [
  { command: 'bancos', description: 'Listar contas e saldo total' },
  { command: 'novo_banco', description: 'Cadastrar um banco' },
  { command: 'atualizar_saldo', description: 'Corrigir o saldo de um banco' },
  { command: 'apagar_banco', description: 'Remover um banco' },
  { command: 'gasto', description: 'Registrar uma despesa' },
  { command: 'receita', description: 'Registrar uma entrada' },
  { command: 'pagar_conta', description: 'Dar baixa em contas pendentes' },
  { command: 'editar', description: 'Editar ou excluir um lançamento' },
  { command: 'mes', description: 'Balanço do mês atual' },
  { command: 'grafico', description: 'Gráfico de gastos por categoria' },
  { command: 'lucro', description: 'Gráfico de ganhos (receitas + empréstimos)' },
  { command: 'resultado', description: 'Comparativo entradas x gastos' },
  { command: 'orcamentos', description: 'Orçamentos e consumo do mês' },
  { command: 'novo_orcamento', description: 'Definir limite de uma categoria' },
  { command: 'apagar_orcamento', description: 'Remover um orçamento' },
  { command: 'recorrencias', description: 'Assinaturas e contas recorrentes' },
  { command: 'nova_recorrencia', description: 'Cadastrar uma recorrência' },
  { command: 'pausar_recorrencia', description: 'Pausar ou retomar uma recorrência' },
  { command: 'apagar_recorrencia', description: 'Remover uma recorrência' },
  { command: 'novo_emprestimo', description: 'Registrar um empréstimo' },
  { command: 'emprestimos', description: 'Empréstimos a receber' },
  { command: 'quitar_emprestimo', description: 'Dar baixa em um empréstimo' },
  { command: 'caixinhas', description: 'Suas caixinhas e o progresso' },
  { command: 'nova_caixinha', description: 'Criar uma caixinha' },
  { command: 'guardar', description: 'Guardar dinheiro numa caixinha' },
  { command: 'resgatar', description: 'Resgatar de uma caixinha' },
  { command: 'atualizar_caixinha', description: 'Registrar rendimento de uma caixinha' },
  { command: 'apagar_caixinha', description: 'Remover uma caixinha' },
  { command: 'patrimonio', description: 'Total: bancos + caixinhas' },
  { command: 'help', description: 'Ajuda e lista de comandos' },
];

// Texto do /help e do /start, agrupado por módulo.
export const TEXTO_AJUDA = [
  '🤖 FinanceBot — comandos',
  '',
  '🏦 Bancos',
  '• /bancos — contas e saldo total',
  '• /novo_banco — cadastrar banco',
  '• /atualizar_saldo — corrigir saldo',
  '• /apagar_banco — remover banco',
  '',
  '💸 Fluxo de caixa',
  '• /gasto — registrar despesa',
  '• /receita — registrar entrada',
  '• /pagar_conta — dar baixa em pendências',
  '• /editar — editar ou excluir um lançamento',
  '• /mes — balanço do mês',
  '',
  '📊 Gráficos',
  '• /grafico — gastos por categoria',
  '• /lucro — ganhos (receitas + empréstimos)',
  '• /resultado — entradas x gastos',
  '',
  '🎯 Orçamentos',
  '• /orcamentos — limites e consumo do mês',
  '• /novo_orcamento — definir limite de categoria',
  '• /apagar_orcamento — remover orçamento',
  '',
  '🔁 Recorrências',
  '• /recorrencias — listar assinaturas/contas fixas',
  '• /nova_recorrencia — cadastrar',
  '• /pausar_recorrencia — pausar ou retomar',
  '• /apagar_recorrencia — remover',
  '',
  '🤝 Empréstimos',
  '• /novo_emprestimo — registrar empréstimo',
  '• /emprestimos — a receber',
  '• /quitar_emprestimo — dar baixa',
  '',
  '🐷 Caixinhas',
  '• /caixinhas — progresso das caixinhas',
  '• /nova_caixinha — criar caixinha',
  '• /guardar — guardar dinheiro',
  '• /resgatar — resgatar dinheiro',
  '• /atualizar_caixinha — registrar rendimento',
  '• /apagar_caixinha — remover caixinha',
  '• /patrimonio — bancos + caixinhas',
  '',
  'ℹ️ Dentro de um cadastro, /cancelar aborta.',
].join('\n');

// Registra o menu de comandos no Telegram.
export async function configurarMenuDeComandos() {
  await bot.telegram.setMyCommands(COMANDOS);
}
